kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: mauriceo/mandelbrot
    tags:
      - latest
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
      - master
    event:
      - push
      - pull_request

- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 
      from_secret: tg_bot_token
    to: -1001411660806